#pipeline name/workflow name
name: csv file validator

#set trigger
on:
  push:
    branches:
      - main
  
  workflow_dispatch:

#create jobs
jobs:
  validate-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code / download code
        uses: actions/checkout@v7

      - name: run validate employee.csv
        run: python validate_employee.csv

      - name: move data to target
        run: echo 'move data'